### ISSUE TITLE
Naming in the list

### ISSUE THREAD

**Issue by WhoMI7** [JKubovy/MPV-Watch-Later-OSD-Menu#3]
Filename saved in `watch-later`: `# D:\Videos\Courses\School of Motion\E Next-Level Techniques\1 Expression Session\Week 3 Properties Management\4.Lesson 4 Full Tilt Blur\1\1.Lesson 4- Full Tilt Blur.mkv` 

Filename using mediainfo: `1.Lesson 4- Full Tilt Blur.mkv`, there is no `media-title` to the file.

If these are file name then why is it showing it as 
![image](https://github.com/JKubovy/MPV-Watch-Later-OSD-Menu/assets/93109835/d6e71f6b-53b2-4921-a7a0-6a6d4d5d70f0)
in menu?
Maybe because filename starts with a number?
Cause any file that had number before an alphabet was reduced to that number as a filename in the menu?
Is this a known issue? Or a bug? A valid new issue?

**Comment by JKubovy** [comment]
I will look in to it. It seems to me it could be a bug in filename parsing.

**Comment by JKubovy** [comment]
It was a bug and it should be fix in [eb59233](https://github.com/JKubovy/MPV-Watch-Later-OSD-Menu/commit/eb5923301a1d3ee195b7a3a10cd1562245023229) commit.

If it doesn't work open the issue again.
